version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
      #!/bin/bash
      # Remove any existing index files to prevent conflicts
      rm -f /var/www/html/index.php
      rm -f /var/www/html/index.html
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

